
name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
    - name: Run unit tests
      run: |
        cd /workspace
        python -m pytest tests/test_unit.py -v
    - name: Run integration tests
      run: |
        cd /workspace
        python -m pytest tests/test_integration.py -v
